"""set unique false on contacts email

Revision ID: 20e9d0df4022
Revises: ecfa3ab5de85
Create Date: 2023-07-15 17:09:45.666380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e9d0df4022'
down_revision = 'ecfa3ab5de85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Contacts_phone_key', 'Contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Contacts_phone_key', 'Contacts', ['phone'])
    # ### end Alembic commands ###
