"""set unique=False on Contacts.email

Revision ID: ecfa3ab5de85
Revises: bc58175d5fd4
Create Date: 2023-07-15 16:56:14.048554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfa3ab5de85'
down_revision = 'bc58175d5fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Contacts_email_key', 'Contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Contacts_email_key', 'Contacts', ['email'])
    # ### end Alembic commands ###
